services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: myadmin
      MINIO_ROOT_PASSWORD: mysecurepassword
    volumes:
      - ./docker/minio/data:/data  # Usando um diretório relativo dentro do seu projeto
    command: server /data --console-address ":9001"
    networks:
      - api-network

  pg:
    container_name: api-seplag
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=seplag
    volumes:
      - pg_data:/bitnami/postgresql/data
    networks:
      - api-network

volumes:
  pg_data:

networks:
  api-network:
    driver: bridge
