services:
    php:
        build:
            context: ./docker/php
        container_name: seplag-php
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - api-network
        depends_on:
            - pg

    nginx:
        image: nginx:latest
        container_name: seplag-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - api-network

    pg:
        container_name: pgsql
        image: bitnami/postgresql:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=seplag
        volumes:
            - pg_data:/bitnami/postgresql
        networks:
            - api-network

    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: myadmin
            MINIO_ROOT_PASSWORD: mysecurepassword
        volumes:
            - ./docker/minio/data:/data
            - ./docker/minio/init.sh:/docker-entrypoint-initbucket.d/init.sh
        command: server /data --console-address ":9001"
        networks:
            - api-network

volumes:
    pg_data:

networks:
    api-network:
        driver: bridge
