services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - api-network
        depends_on:
            - pg

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - api-network

    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: myadmin
            MINIO_ROOT_PASSWORD: mysecurepassword
        volumes:
            - ./docker/minio/data:/data
        command: server /data --console-address ":9001"
        networks:
            - api-network

    pg:
        container_name: api-seplag
        image: bitnami/postgresql:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=seplag
        volumes:
            - pg_data:/bitnami/postgresql
        networks:
            - api-network

volumes:
    pg_data:

networks:
    api-network:
        driver: bridge
